export default [
  'CREATE_USER',
  'READ_USER',
  'UPDATE_USER',
  'CREATE_COMMAND',
  'READ_COMMAND',
  'UPDATE_COMMAND',
  'CREATE_GROUP',
  'READ_GROUP',
  'UPDATE_GROUP',
  'CREATE_ROLE',
  'READ_ROLE',
  'UPDATE_ROLE',
  'EXECUTE_GROUP'
];
